remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Introduction to Data Science
description: Graduate-level course materials covering fundamental concepts in data science
show_downloads: true

# Theme customization
github:
  is_project_page: true
  repository_url: https://github.com/wmjs/intro-ds-materials
